In [1]:
import numpy as np

a=np.array([12,34,56,78])
b=np.array([32,43,54,65])

result=np.concatenate((a,b))

print(result)

[12 34 56 78 32 43 54 65]


In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))

print(result)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.hstack((a,b))

print(result)

[1 2 3 4 5 6]


In [8]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

result = np.split(arr, 3)

print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [9]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])

result = np.array_split(arr, 3)

print(result)

[array([10, 20, 30]), array([40, 50]), array([60, 70])]
