2D MATRIX



In [2]:
import numpy as np

arr = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print(arr)


[[1 2 3]
 [4 5 6]]


3D MATRIX



In [5]:
import numpy as np

arr = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ]
    ]
)

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


ndim



In [11]:
import numpy as np

arr = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ]
    ]
)

print(arr)

print("Dimension:",arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension: 3


Access an Element in a 3D Array



In [12]:
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr[1][1][1])

8


Create Arrays with Different Dimensions



In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([
    [1, 2],
    [3, 4]
])

arr3 = np.array([
    [[1, 2], [3, 4]]
])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3
