In [1]:
import numpy as np

arr = np.random.rand(5)

print(arr)

[0.35392417 0.53749046 0.27389036 0.07387235 0.80132374]


In [2]:
import numpy as np

arr = np.random.randint(1, 101, 5)

print(arr)

[ 80  35  55 100  11]


In [3]:
import numpy as np

arr = np.random.randn(5)

print(arr)

[-0.08006825 -0.1346044  -0.37257958 -0.78665209 -0.81767222]


In [6]:
import numpy as np

departments = np.array(["CSE", "IT", "ECE", "EEE"])

result = np.random.choice(departments, 4)

print(result)

['IT' 'CSE' 'CSE' 'IT']


In [9]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

np.random.shuffle(arr)

print(arr)

[50 20 30 10 40]
