In [1]:
import numpy as np

arr = np.array([45, 12, 78, 23, 56])

print(np.min(arr))

12


In [2]:
import numpy as np

arr = np.array([45, 12, 78, 23, 56])

print(np.max(arr))

78


In [3]:
import numpy as np

arr = np.array([45, 12, 78, 23, 56])

print(np.argmin(arr))

1


In [4]:
import numpy as np

arr = np.array([45, 12, 78, 23, 56])

print(np.argmax(arr))

2


In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(np.median(arr))

30.0


In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(np.var(arr))

200.0


In [10]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(np.percentile(arr, 50))

30.0


In [11]:
import numpy as np

arr = np.array([10, 20, 10, 30, 20, 40, 30])

print(np.unique(arr))

[10 20 30 40]


In [12]:
import numpy as np

arr = np.array([50, 20, 80, 10, 40])

print(np.sort(arr))

[10 20 40 50 80]


In [13]:
import numpy as np

arr = np.array([50, 20, 80, 10, 40])

print(np.argsort(arr))

[3 1 4 0 2]
