In [1]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr + 5)

[15 25 35]


In [2]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr * 2)

[20 40 60]


In [3]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

values = np.array([1, 2, 3])

print(arr + values)

[[11 22 33]
 [41 52 63]]


In [4]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

values = np.array([
    [1],
    [2],
    [3]
])

print(arr + values)

[[11 21 31]
 [42 52 62]
 [73 83 93]]


In [5]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20, 30])

print(a + b)

[[11 22 33]
 [14 25 36]]
