1.Slice a 1D Array

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])

[20 30 40]


2.Slice Rows in a 2D Array

In [2]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[0:2])

[[1 2 3]
 [4 5 6]]


3.Slice Columns

In [4]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[0:2, 0:2])

[[1 2]
 [4 5]]


4.Step Slicing

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[::2])

[10 30 50]


5.Reverse an Array

In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[::-1])

[50 40 30 20 10]
