Save Array using np.save()

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

np.save("numbers.npy", arr)

print("Array Saved Successfully")

Array Saved Successfully


Load Array using np.load()

In [2]:
import numpy as np

new_arr = np.load("numbers.npy")

print(new_arr)

[1 2 3 4 5 6]


Save as Text using np.savetxt()

In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

np.savetxt("numbers.txt", arr)

print("File saved")

File saved


Load Text using np.loadtxt()

In [5]:
import numpy as np

arr = np.loadtxt("numbers.txt")

print(arr)

[10. 20. 30. 40. 50.]


Save Multiple Arrays using np.savez()

In [8]:
import numpy as np

names = np.array(["Arun", "Priya", "Rahul"])

marks = np.array([85, 92, 78])

np.savez("students.npz", names=names, marks=marks)

print("Arrays saved")

data = np.load("students.npz")

print(data["names"])
print(data["marks"])

Arrays saved
['Arun' 'Priya' 'Rahul']
[85 92 78]
