1.Addition

In [1]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)

[11 22 33]


2.Subtraction

In [2]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a - b)

[ 9 18 27]


3.Multiplication

In [3]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a * b)

[10 40 90]


4.Division

In [6]:
import numpy as np

a = np.array([20, 30, 40])
b = np.array([2, 3, 4])

print(a / b)


[10. 10. 10.]


5.Modulus

In [7]:
import numpy as np

a = np.array([20, 30, 40])
b = np.array([2, 3, 4])

print(a % b)

[0 0 0]


6.Power

In [8]:
import numpy as np

arr = np.array([2, 3, 4])

print(arr ** 2)

[ 4  9 16]


7.Square Root

In [9]:
import numpy as np

arr = np.array([4, 9, 16, 25])

print(np.sqrt(arr))

[2. 3. 4. 5.]


8.Sum

In [10]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(np.sum(arr))

100


9.Mean

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(np.mean(arr))

25.0


10.Standard Deviation

In [12]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(np.std(arr))

11.180339887498949
