Filter Values Greater Than a Number

In [2]:
import numpy as np

arr = np.array([10, 25, 50, 75, 90])

result = arr[arr > 50]

print(result)

[75 90]


Filter Even Numbers

In [3]:
import numpy as np

arr = np.array([10, 15, 20, 25, 30, 35])

result = arr[arr % 2 == 0]

print(result)

[10 20 30]


Filter Odd Numbers

In [4]:
import numpy as np

arr = np.array([10, 15, 20, 25, 30, 35])

result = arr[arr % 2 != 0]

print(result)

[15 25 35]


Use np.where()

In [6]:
import numpy as np

arr = np.array([10, 50, 70, 20, 90])

result = np.where(arr > 50,arr,0)

print(result)

[ 0  0 70  0 90]


Replace Values using Boolean Indexing

In [ ]:
import numpy as np

marks = np.array([85, 42, 30, 75, 25, 90])

marks[marks < 35] = 0
print(marks)

[85 42  0 75  0 90]
