In [1]:
import numpy as np

arr = np.zeros((3, 4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
import numpy as np

arr = np.ones((2, 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
import numpy as np

arr = np.full((2, 3), 100)

print(arr)

[[100 100 100]
 [100 100 100]]


In [4]:
import numpy as np

arr = np.eye(4)

print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
import numpy as np

arr = np.arange(1,11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
import numpy as np

arr = np.empty((2, 3))

print(arr)

[[4.94e-322 4.94e-322 4.94e-322]
 [4.94e-322 4.94e-322 4.94e-322]]


In [9]:
import numpy as np

arr = np.diag([10, 20, 30])

print(arr)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [10]:
import numpy as np

arr = np.linspace(0, 10, 5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]
