In [2]:
import numpy as np

arr = np.arange(15)

print(arr)
print(arr.reshape(3, -1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.flatten())

[1 2 3 4 5 6]


In [4]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.ravel())

[1 2 3 4 5 6]


In [5]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = np.resize(arr, (2, 3))

print(new_arr)

[[1 2 3]
 [4 5 6]]
